# Generated by Django 3.2.3 on 2021-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210526_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('wallet', 'wallet')], default='cash', max_length=15),
        ),
    ]
