# Generated by Django 3.2.3 on 2021-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
